version: '3'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    working_dir: /var/www
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./:/var/www
      - ./docker/server/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/server/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/server
    container_name: php
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    depends_on: 
      - db

  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: clothing_shop
    volumes: 
      - ./docker/db/mysql:/var/lib/mysql

  composer:
    image: composer
    container_name: composer
    volumes: 
      - ./:/var/www
    working_dir: /var/www
    command: composer install

  cache:
    image: redis:5.0
    container_name: cache
    ports:
      - 6379:6379
