version: '3'

services:
  server:
    build: ./docker/server
    environment: 
      - APACHE_RUN_USER=#1000
    volumes: 
      - ./:/var/www
      - ./docker/server/sites-available:/etc/apache2/sites-available
    ports: 
      - 80:80
    working_dir: /var/www
    command: /tmp/run.sh
    depends_on: db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: clothing_shop
    volumes: 
      - ./docker/db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 5080:8080

  composer:
    image: composer
    volumes: 
      - ./:/var/www
    working_dir: /var/www
    command: composer install