version: '3'

services:
  server:
    image: ch-server
    container_name: ch-server
    build:
      context: ./docker/server
    environment: 
      - APACHE_RUN_USER=#1000
    volumes: 
      - ./:/var/www
      - ./docker/server/sites-available:/etc/apache2/sites-available
    ports: 
      - 80:80
    working_dir: /var/www
    depends_on: 
      - db
      - cache

  db:
    image: mysql:8.0
    container_name: ch-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: clothing_shop
    volumes: 
      - ./docker/db/mysql:/var/lib/mysql

  composer:
    image: composer
    container_name: ch-composer
    volumes: 
      - ./:/var/www
    working_dir: /var/www
    command: composer install

  cache:
    image: redis:5.0
    container_name: ch-cache
    ports:
      - 6379:6379

  node:
    image: node:8-alpine
    container_name: ch-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm rebuild node-sass && npm install && npm run dev"
